num = int(input('Введите количество элементов списка: '))
my_list = new_list(num)
print(my_list)
print('Сумма нечетных элементов = ', sum_odd_elem(my_list))
print('Сумма четных элементов = ', sum_not_odd_elem(my_list))